apiVersion: batch/v1
kind: CronJob
metadata:
  name: todoapp-cronjob
  namespace: mateapp
spec:
  schedule: "*/4 * * * *"
  concurrencyPolicy: Allow
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: todoapp-health
            image: busyboxplus:curl
            command: ["sh", "-c"]
            args:
              - |
                echo "$(date -Is) curling /api/health";
                curl -sS --max-time 10 http://todoapp:80/api/health || echo "curl failed";
            resources:
              requests:
                cpu: "100m"
                memory: "100Mi"
              limits:
                cpu: "200m"
                memory: "200Mi"